### ISSUE TITLE
关于HappyMybatisMetaObjectHandler 更新时，应该直接获取updateById,updateByDate，还是应该直接set最上下文中用户信息或日期，讨论。

### ISSUE THREAD

**Issue by scwanglijun** [happy-coding-cool/happy-code#1]
关于HappyMybatisMetaObjectHandler 更新时，应该直接获取updateById,updateByDate，还是应该直接set最上下文中用户信息或日期。
1、如直接获取updateById,UpdateByDate, 第一次如查有值的情况，不更新的话，就是第一次insert的值。
2、直接setter的话，有一个情况，如果用户想指定更新人，更新时间，就不能更新。比较尴尬。

JPA的做法，是直接获取上下文用户信息或new Date（）。

**Comment by pzsoftchen** [comment]
代码里已经做了这个考虑：优先以用户传入的值为主，如果没有值才会从上下文里获取

**Comment by pzsoftchen** [comment]
> 关于HappyMybatisMetaObjectHandler 更新时，应该直接获取updateById,updateByDate，还是应该直接set最上下文中用户信息或日期。
> 1、如直接获取updateById,UpdateByDate, 第一次如查有值的情况，不更新的话，就是第一次insert的值。
> 2、直接setter的话，有一个情况，如果用户想指定更新人，更新时间，就不能更新。比较尴尬。
> 
> JPA的做法，是直接获取上下文用户信息或new Date（）。

代码里已经做了这个考虑：优先以用户传入的值为主，如果没有值才会从上下文里获取 @scwanglijun

**Comment by scwanglijun** [comment]
非常感谢回复，当从数据取数据出来更新，实际更新字段是有值的，此更新方法，还得把更新人，更新时间设置为空，才能更新更新时间和更新人。

**Comment by scwanglijun** [comment]
非常感谢回复，当从数据取数据出来更新，实际更新字段是有值的，此更新方法，还得把更新人，更新时间设置为空，才能更新更新时间和更新人。

**Comment by pzsoftchen** [comment]
> 非常感谢回复，当从数据取数据出来更新，实际更新字段是有值的，此更新方法，还得把更新人，更新时间设置为空，才能更新更新时间和更新人。

既希望程序自动维护又希望可以自由设值，这是一个不能两全的场景，因此这些数据库约定的字段一般都是放到PO的基类里的，一般情况下都由程序来自动维护(平时不需要关心这些字段)，必要情况下才手动设值(此时用户是清楚的知道要自己维护的)
